language: node_js
node_js:
- 6
- 7
cache: yarn
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: n6yvqFUfF6UPxwWmYOy62EvXKSO300SAPOyRwp8ZUqx9sHEBtv4+2Ne8CiIuxP7MuFQs9SnGqT7ZVDtZfClpkFFErVQXe/uEOf9u7Sa5XUh05sOqKBGIE02Rjq9l3pXOVWSebzprO5KwUR9JNMe6CUJTTroc/noPciO7mRpOEm+UsSCs5vaYPlSSijiDow+ZCtMbD8h21LZcZoZqa1CbZCJuIAuF8UZ5F3wmDxZQ3SA8AfGh4MKFUmsLPaOK1OwZhgVKvw2hn0AoWNrbV/rMraYNa9ySjaHZUJpkYPYeeRpVisqcX2UI6nStnPC0wmZamkPrs4k+GjLcvJBSF65CsE6clnwuPZlX9f7LyJdpnpGTcuaCUV5xqkrM7Xj66Ta5ywpF1Kruy54BlwefucBIFzI/cKUxVnn2aH41d6h4jfncj23k/kmbjSKZ6CZN+0sTIY0lzJvhmmyxgEJztPPREZnzS7duMQe+lqnN1YHl7LVR6GWluS/8kB0ZP64pnH66MzNB93s8VYldWd/1EjippBNciECYCNgZgn0D/8QNkNIZ4k0pRzXucdg+cKZTMo1jp9wla8syinLo5L6joR2WyJz1r+Z4o99NwiRMbtpyJOQbnTWBf+Ii87vys79hh6Rv+87J8snOYEfJNDjyZ5M5ZlGuYcfIdiDXX8xgxvTuzQk=
  on:
    tags: true
    repo: intel-hpdd/fp
