sudo: required
language: node_js
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
      node_js:
        - 6
      name: "Lint & Test"
      script:
        - npm run flow
        - npm run eslint
        - npm run test
    - stage: deploy-npm
      name: "npm Deploy"
      script: skip
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
stages:
  - test
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+$
